/**
 * Product vocabulary (FR-10.11). Git terms appear only under Diagnostics.
 */
export const strings = {
  appName: "Converge",
  provider: "Provider",
  repository: "Repository",
  base: "Base",
  includedChanges: "Included PRs/MRs",
  combinedReview: "Combined Review",
  conflict: "Conflict",
  finishReview: "Finish Review",
  discardReview: "Discard Review",
  buildReview: "Build Review",
  diagnostics: "Diagnostics",
  expired: "expired",
  hoursLeft: (hours: number) => `${hours}h left`,
  minutesLeft: (minutes: number) => `${minutes}m left`,
  underMinuteLeft: "<1m left",
  reviewUnavailableTitle: "This review is no longer available",
  reviewUnavailableDescription: "Start a new review to continue.",
  startNewReview: "Start a new review",
  resumeReview: "Resume a review",
  resume: "Resume",
  discard: "Discard",
  cancel: "Cancel",
  started: "started",
  expires: "expires",
  statusReady: "Ready",
  statusBuilding: "Building",
  statusFailed: "Failed",
  discardConfirmSuffix: "This cannot be undone.",
  noReviewsInProgressTitle: "No reviews in progress.",
  noReviewsInProgressDescription: "Start one by choosing a repository below.",
  reviewsUnavailableTitle: "Could not load reviews in progress",
  reviewDiscardFailed: "The review could not be discarded.",
  reviewsInProgressCount: "reviews in progress",
  noTicket: "No ticket",
  reviews: "Reviews",
  newReview: "New review",
  startNewReviewRow: "Start a new review",
  chooseChanges: "Choose changes",
  noOpenReviews: "No open reviews",
  hideDependencyBots: "Hide dependency bots",
  groupByTicket: "Group by ticket",
  selectOneOrMoreChanges: "Select one or more changes",
  appliedOldestToNewest: "applied oldest → newest",
  viewed: "Viewed",
  nextFile: "Next file",
  backToFirstFile: "Back to first file",
  copyPath: "Copy path",
  inspect: "Inspect",
  open: "Open",
  show: "Show",
  clear: "Clear",
  details: "details",
} as const;
