/**
 * Product vocabulary (FR-10.11). Git terms appear only under Diagnostics.
 */
export const strings = {
  provider: "Provider",
  repository: "Repository",
  base: "Base",
  includedChanges: "Included PRs/MRs",
  combinedReview: "Combined Review",
  conflict: "Conflict",
  finishReview: "Finish Review",
  discardReview: "Discard Review",
  buildReview: "Build Review",
  diagnostics: "Diagnostics",
  expired: "expired",
  reviewUnavailableTitle: "This review is no longer available",
  reviewUnavailableDescription: "Start a new review to continue.",
  startNewReview: "Start a new review",
  resumeReview: "Resume a review",
  resume: "Resume",
  discard: "Discard",
  cancel: "Cancel",
  started: "started",
  expires: "expires",
  statusReady: "Ready",
  statusBuilding: "Building",
  statusFailed: "Failed",
  discardConfirmSuffix: "This cannot be undone.",
  noReviewsInProgressTitle: "No reviews in progress.",
  noReviewsInProgressDescription: "Start one by choosing a repository below.",
  reviewsUnavailableTitle: "Could not load reviews in progress",
  reviewDiscardFailed: "The review could not be discarded.",
} as const;
