/**
 * Product vocabulary (FR-10.11). Git terms appear only under Diagnostics.
 */
export const strings = {
  appName: "Converge",
  provider: "Provider",
  repository: "Repository",
  base: "Base",
  includedChanges: "Included PRs/MRs",
  combinedReview: "Combined Review",
  conflict: "Conflict",
  finishReview: "Finish Review",
  discardReview: "Discard Review",
  buildReview: "Build Review",
  diagnostics: "Diagnostics",
  expired: "expired",
  hoursLeft: (hours: number) => `${hours}h left`,
  minutesLeft: (minutes: number) => `${minutes}m left`,
  underMinuteLeft: "<1m left",
  reviewUnavailableTitle: "This review is no longer available",
  reviewUnavailableDescription: "Start a new review to continue.",
  startNewReview: "Start a new review",
  resumeReview: "Resume a review",
  resume: "Resume",
  discard: "Discard",
  cancel: "Cancel",
  started: "started",
  expires: "expires",
  statusReady: "Ready",
  statusBuilding: "Building",
  statusFailed: "Failed",
  discardConfirmSuffix: "This cannot be undone.",
  noReviewsInProgressTitle: "No reviews in progress.",
  noReviewsInProgressDescription: "Start one by choosing a repository below.",
  reviewsUnavailableTitle: "Could not load reviews in progress",
  reviewDiscardFailed: "The review could not be discarded.",
  reviewsInProgressCount: "reviews in progress",
  noTicket: "No ticket",
  reviews: "Reviews",
  newReview: "New review",
  startNewReviewRow: "Start a new review",
  chooseChanges: "Choose changes",
  noOpenReviews: "No open reviews",
  hideDependencyBots: "Hide dependency bots",
  groupByTicket: "Group by ticket",
  selectOneOrMoreChanges: "Select one or more changes",
  appliedOldestToNewest: "applied oldest → newest",
  viewed: "Viewed",
  nextFile: "Next file",
  backToFirstFile: "Back to first file",
  copyPath: "Copy path",
  inspect: "Inspect",
  open: "Open",
  show: "Show",
  clear: "Clear",
  details: "details",
  repositoryNotFound: (fullName: string) => `${fullName} could not be found on this provider.`,
  repositoryInvalidFormat: "That doesn't look like a repository name or URL.",
  repositoryCheckFailed: "That repository could not be checked.",
  selectAProvider: "Select a provider",
  searchRepositoriesPlaceholder: "Search repositories, or paste owner/name",
  noRepositoriesMatchSearch: "No repositories match that search.",
  pickProviderAndRepository: "Pick a provider and a repository.",
  reviewsPageDescription: "Resume a review in progress, or start a new one.",
  columnStatus: "Status",
  columnProgress: "Progress",
  columnExpires: "Expires",
  columnActions: "Actions",
  filterBranchesPlaceholder: "Filter branches",
  noBranchesMatchFilter: "No branches match that filter.",
  branchDefault: "default",
  useTypedBranch: (name: string) => `Use “${name}”`,
  shownOfTotal: (shown: number, total: number) => `${shown} of ${total} shown`,
  noMergedChanges: "No merged PRs/MRs",
  noMergedChangesDescription: "Nothing matches this base branch and these filters.",
  columnNumber: "Number",
  columnTitle: "Title",
  columnAuthor: "Author",
  columnMerged: "Merged",
  columnSourceBranch: "Source branch",
  selectAllVisibleChanges: "Select all visible changes",
  selectHash: (number: number) => `Select #${number}`,
  selectAllInGroup: (count: number) => `Select all ${count}`,
  deselectAll: "Deselect all",
  changesCount: (count: number) => `${count} changes`,
  changesHiddenBy: (count: number) => `${count} changes hidden by “${strings.hideDependencyBots}”`,
  couldNotLoadBranches: "Could not load branches",
  // Kept title-cased: "Included PRs/MRs" is product vocabulary (FR-10.11), so
  // it must not be lowercased to fit a sentence.
  couldNotLoadIncludedChanges: "Could not load Included PRs/MRs",
  filterFilesPlaceholder: "Filter files",
  changedFiles: "Changed files",
  markFileViewed: (name: string) => `Mark ${name} viewed`,
  collapseDirectory: (name: string) => `Collapse ${name}`,
  expandDirectory: (name: string) => `Expand ${name}`,
  openInProvider: (providerName: string) => `Open in ${providerName}`,
  pathCopied: "Path copied",
  pathCopyFailed: "The path could not be copied.",
  fileOfTotal: (index: number, total: number) => `File ${index} of ${total}`,
  couldNotLoadFileDiff: "Could not load this file's diff",
} as const;
